# Generated by Django 4.2.5 on 2023-09-20 18:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0003_remove_requesthelp__from_remove_requestitems__from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RescueTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=50)),
                ("address_line_1", models.CharField(max_length=30)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("pincode", models.BigIntegerField()),
                ("gps_coordinate", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=100)),
                (
                    "category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_category", models.CharField(max_length=100)),
                (
                    "requested_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                (
                    "requested_quantity",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "requested_items_desc",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                ("deadline", models.DateField()),
                ("priority_call", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                (
                    "_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.rescueteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "categories_requested",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=None
                    ),
                ),
                ("deadline", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("priority_call", models.BooleanField(default=False)),
                (
                    "_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.rescueteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.rescueteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
