# Generated by Django 4.2.5 on 2023-09-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requesthelp",
            name="_from",
        ),
        migrations.RemoveField(
            model_name="requestitems",
            name="_from",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="RequestHelp",
        ),
        migrations.DeleteModel(
            name="RequestItems",
        ),
        migrations.DeleteModel(
            name="RescueTeam",
        ),
    ]
