# Generated by Django 4.2.5 on 2023-09-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestItems",
        ),
    ]
