# Generated by Django 4.2.5 on 2023-09-21 20:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_delete_requestitems"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_category", models.CharField(max_length=100)),
                (
                    "requested_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                (
                    "requested_quantity",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "requested_items_desc",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                ("deadline", models.DateField()),
                ("priority_call", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("answered", models.BooleanField(default=False)),
                ("answeredBy", models.CharField(max_length=50, null=True)),
                (
                    "_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.rescueteam",
                    ),
                ),
            ],
        ),
    ]
